### ISSUE TITLE
Dropwizard 0.8 support?

### ISSUE THREAD

**Issue by jplock** [yammer/tenacity#16]
Would you be interested in a PR to upgrade to Dropwizard 0.8.0 now that it's out?

**Comment by thesmith** [comment]
Yes please :)

@velocipedist have you done this yet?

**Comment by chrisgray** [comment]
Going to be done soon!

Trying to get 0.5.0 out (moving to Hystrix 1.4.0)

Then I was going to try DW8. Also I'm trying to figure out how to maintain DW7/DW8 artifacts without too much overhead. I was thinking simply to move to 0.6.0 for DW8+ releases and using 0.5.x for any releases for DW7.

**Comment by velocipedist** [comment]
We are working on it already. I detected at least one bug in 0.8.0 that blocks us. So please be patient.

**Comment by chrisgray** [comment]
0.6.0 supports dropwizard 0.8.1
