### ISSUE TITLE
There's no way for to set executionIsolationSemaphoreMaxConcurrentRequests property

### ISSUE THREAD

**Issue by shtratos** [yammer/tenacity#22]
Without this it's impossible to use TenacityObservableCommand with more than 10 concurrent requests.
And there's no way to switch TenacityObservableCommand to using threadpool since it hides original HystrixObservableCommand constructor.

The same is true for fallbackIsolationSemaphoreMaxConcurrentRequests property.

Also it would be nice to configure those properties in breakerbox.

**Comment by chrisgray** [comment]
This is definitely a limitation indeed. I'll get the ability to configure the semaphores and have the ability to tune these in breakerbox immediately.

The UI in breakerbox could definitely be improved such that it allows you to switch between the two isolation modes (semaphore and thread), but this will be for a future release.

 Adding the ability to move HystrixObservableCommand over to using a threadpool might a bit more involved. It seems highly intended to be used within semaphore isolation.

**Comment by chrisgray** [comment]
This is now fixed in the release of 0.5.3 (Tenacity) and 0.1.4 for Breakerbox!
