### ISSUE TITLE
Null Pointer Exception when using HystrixObservableCollapser

### ISSUE THREAD

**Issue by arthurtsang** [yammer/tenacity#23]
I've created a Observable Collapser following this.  https://github.com/Netflix/Hystrix/pull/261
And when I call HystrixObservableCollapser.toObservable(), I get a NPE at HystrixObservableCollapser.toObservable(Scheduler) as collapserFactory.getRequestCollapser(collapserInstanceWrapper) returns which in the end comes from ManagedConcurrencyStrategy.getRequestVariable().get() which is hardcoded to return null.

**Comment by chrisgray** [comment]
I'll take a look and get a fix out for this.

**Comment by chrisgray** [comment]
This is fixed with the 0.6.1 and 0.5.5 (backport dw0.7.x) releases
