### ISSUE TITLE
Upgrade to Hystrix 1.5.12

### ISSUE THREAD

**Issue by andredasilvapinto** [yammer/tenacity#42]
Changelog:
https://github.com/Netflix/Hystrix/commit/dbc7429dbf7b82b4f27610f0bfc2e187106179ad

**Comment by chrisgray** [comment]
I'll get this done

**Comment by chrisgray** [comment]
This is now in [Release 1.1.2](https://github.com/yammer/tenacity/releases/tag/tenacity-parent-1.1.2)

**Comment by TurtleShip** [comment]
👍

**Comment by andredasilvapinto** [comment]
Thanks!
